name: Deploy Ignite Timer
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install 

      - name: Linting
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm runtest:ci